-d C:\Users\Admin\Documents\fpga_project_test36\impl\gwsynthesis\fpga_project_test36.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-UV9QN88PC6/I5
-cst C:\Users\Admin\Documents\fpga_project_test36\src\fpga_project_test36.cst
-cfg C:\Users\Admin\Documents\fpga_project_test36\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
